[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "volsync"
version = "0.1.0"
description = "A production-ready tool for syncing files to Databricks volumes"
readme = "README.md"
requires-python = ">=3.12,<3.13"
license = {text = "MIT"}
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "click>=8.1.8",
    "databricks-sdk>=0.58.0",
]
