
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "lightning"
version = "0.1.0"
description = "A production-ready Databricks job for processing PDF documents using OCR via Claude AI"
requires-python = ">=3.12,<3.13"
license = {text = "MIT"}
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
]
